name: "Compare S3 objects to local directory action"
description: "Compare a remote path from S3 to a local GitHub repo path"
inputs:
  access_key_id:
    description: "S3 or compatible access key ID"
    required: true
    default: ""
  bucket_name:
    description: "Bucket name"
    required: true
    default: ""
  bucket_endpoint:
    description: "The S3 or compatible endpoint to connect to"
    required: true
    default: ""
  bucket_path:
    description: "The path in the bucket that will be compared to local"
    required: true
    default: ""
  local_path:
    description: "The local path to compare with bucket path"
    required: true
    default: ""
  max_keys:
    description: "boto3 maxKeys setting (int) - increase or decrease at will"
    required: false
    default: 50
  region:
    description: "The S3 bucket region"
    required: true
    default: ""
  secret_access_key:
    description: "The secret access key used to authenticate to the bucket"
    required: true
    default: ""
runs:
  using: "docker"
  image: 'Dockerfile'
  env:
    - INPUT_ACCESS_KEY_ID: ${{ input.access_key_id }}
    - INPUT_BUCKET_NAME: ${{ input.bucket_name }}
    - INPUT_BUCKET_ENDPOINT: ${{ input.bucket_endpoint }}
    - INPUT_BUCKET_PATH: ${{ input.bucket_path }}
    - INPUT_LOCAL_PATH: ${{ input.local_path }}
    - INPUT_MAX_KEYS: ${{ input.max_keys }}
    - INPUT_REGION: ${{ input.region }}
    - INPUT_SECRET_ACCESS_KEY: ${{ input.secret_access_key }}
